### ISSUE TITLE
Extension signing

### ISSUE THREAD

**Issue by falzm** [Zegnat/feedbin-link-opener-firefox#1]
Hi! Firefox now [disables unsigned extensions](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct#w_what-can-i-do-if-firefox-disables-an-installed-add-on), could you please sign yours? It's very useful 😁

Thank you in advance!

**Comment by Zegnat** [comment]
Oh definitely, totally forgot about it. I might have time this weekend, else I will put it on the calendar for Monday. Thanks for the reminder.

**Comment by falzm** [comment]
Great, thank you!

**Comment by Zegnat** [comment]
I have just pushed [version 0.2.0](https://github.com/Zegnat/feedbin-link-opener-firefox/releases/tag/v0.2.0) with a signed XPI.

**Comment by falzm** [comment]
Awesome, thanks again!
